import type { NormalizedChannel } from "../models";
import { deriveRegion } from "../region";

export function makeChannel(over: Partial<NormalizedChannel> = {}): NormalizedChannel {
  const district = over.district ?? "6";
  const region = over.region ?? deriveRegion(district, over.call);
  return {
    source_type: "sk6ba",
    source_row: 2,
    source_id: "x",
    type: "Repeater",
    status: "QRV",
    mode_raw: "FM",
    is_analog_fm: true,
    band: "2",
    city: "Borås",
    call: "SK6BA",
    channel: "RV48",
    network: "",
    network_id: "",
    access_raw: "",
    rx_frequency: 145.6,
    tx_shift_raw: "-0.6",
    tx_shift: -0.6,
    shift_unclear: false,
    duplex: "-",
    offset: 0.6,
    ctcss_tx: null,
    uses_1750: false,
    lat: 57.7,
    lng: 12.9,
    locator: "",
    comment: "",
    pack_id: "",
    service: "",
    category: "",
    tags: [],
    label: "",
    name_hint: "",
    tx_frequency: null,
    mode_chirp: "",
    tstep: null,
    tone_raw: "",
    rtone_freq: null,
    ctone_freq: null,
    dtcs_code: "",
    dtcs_polarity: "",
    skip_raw: "",
    tx_allowed: true,
    rx_only: false,
    license_note: "",
    source: "",
    source_url: "",
    inferred_from_range: false,
    generated_name_full: "",
    generated_name_final: "",
    collided: false,
    warnings: [],
    ...over,
    district,
    region,
  };
}
